/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Ecoe;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sahil Sonawane
 */
public class ManageMyProfileJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;    
    private Ecoe ecoe;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientOrganization patientOrganization;
    //private PatientDirectory patientDirectory;
    /**
     * Creates new form ManageMyProfileJPanel
     */
    public ManageMyProfileJPanel(JPanel userProcessContainer,UserAccount userAccount, PatientOrganization patientOrganization, Enterprise enterprise,Ecoe ecoe) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoe = ecoe;
        this.userAccount = userAccount;
        this.patientOrganization = (PatientOrganization)patientOrganization;
        this.enterprise = enterprise;
        //this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createMyProfileJButton = new javax.swing.JButton();
        viewUpdateMyProfileJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 221, 214));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createMyProfileJButton.setBackground(new java.awt.Color(167, 221, 214));
        createMyProfileJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        createMyProfileJButton.setText("Create My Profile");
        createMyProfileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMyProfileJButtonActionPerformed(evt);
            }
        });
        add(createMyProfileJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 210, -1));

        viewUpdateMyProfileJButton.setBackground(new java.awt.Color(167, 221, 214));
        viewUpdateMyProfileJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        viewUpdateMyProfileJButton.setText("View and Update My Profile");
        viewUpdateMyProfileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpdateMyProfileJButtonActionPerformed(evt);
            }
        });
        add(viewUpdateMyProfileJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 250, -1));

        backJButton.setBackground(new java.awt.Color(0, 24, 91));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 24, 91));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 33)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MANAGE MY PROFILE");
        jPanel1.add(jLabel10);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 530, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createMyProfileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMyProfileJButtonActionPerformed
        // TODO add your handling code here:
        CreateMyProfileJPanel panel = new CreateMyProfileJPanel(userProcessContainer,userAccount,patientOrganization,enterprise,ecoe);
        userProcessContainer.add("CreateMyProfileJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createMyProfileJButtonActionPerformed

    private void viewUpdateMyProfileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpdateMyProfileJButtonActionPerformed
        // TODO add your handling code here:
        ViewUpdateMyProfileJPanel panel = new ViewUpdateMyProfileJPanel(userProcessContainer,userAccount,patientOrganization,enterprise,ecoe);
        userProcessContainer.add("ViewUpdateMyProfileJPane", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewUpdateMyProfileJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createMyProfileJButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewUpdateMyProfileJButton;
    // End of variables declaration//GEN-END:variables
}
