/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Ecoe;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class PatientHomePageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientHomePageJPanel
     */
    private JPanel userProcessContainer;    
    private Ecoe ecoe;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientOrganization patientOrganization;
    //private PatientDirectory patientDirectory;
    /**
     * Creates new form PatientHomePageJPanel
     */
    public PatientHomePageJPanel(JPanel userProcessContainer,UserAccount userAccount, PatientOrganization patientOrganization, Enterprise enterprise,Ecoe ecoe) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecoe = ecoe;
        this.userAccount = userAccount;
        this.patientOrganization = (PatientOrganization)patientOrganization;
        this.enterprise = enterprise;
        //this.patientDirectory = patientDirectory;
        patientNameLable.setText(userAccount.getName());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        manageProfileJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        patientNameLable = new javax.swing.JLabel();
        manageVitalSignsAndFitnessRecordJButton = new javax.swing.JButton();
        sendFeedbackJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 221, 214));

        jButton1.setBackground(new java.awt.Color(167, 221, 214));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setText("Check Doctor Response");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        manageProfileJButton.setBackground(new java.awt.Color(167, 221, 214));
        manageProfileJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        manageProfileJButton.setText("Manage My Profile");
        manageProfileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProfileJButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Welcome");
        jLabel1.setEnabled(false);

        patientNameLable.setBackground(new java.awt.Color(0, 153, 153));
        patientNameLable.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        patientNameLable.setForeground(new java.awt.Color(51, 51, 51));
        patientNameLable.setText("<patientName>");
        patientNameLable.setEnabled(false);

        manageVitalSignsAndFitnessRecordJButton.setBackground(new java.awt.Color(167, 221, 214));
        manageVitalSignsAndFitnessRecordJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        manageVitalSignsAndFitnessRecordJButton.setText("Manage My Vital Signs and Fiteness Record");
        manageVitalSignsAndFitnessRecordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVitalSignsAndFitnessRecordJButtonActionPerformed(evt);
            }
        });

        sendFeedbackJButton.setBackground(new java.awt.Color(167, 221, 214));
        sendFeedbackJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        sendFeedbackJButton.setText("Send Feedback");
        sendFeedbackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFeedbackJButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("!");
        jLabel2.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(0, 24, 91));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 33)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MY HOME PAGE");
        jPanel1.add(jLabel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendFeedbackJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageVitalSignsAndFitnessRecordJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(patientNameLable)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(277, 277, 277)
                            .addComponent(manageProfileJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLable)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addComponent(manageProfileJButton)
                .addGap(40, 40, 40)
                .addComponent(manageVitalSignsAndFitnessRecordJButton)
                .addGap(39, 39, 39)
                .addComponent(sendFeedbackJButton)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DoctorRespondJPanel panel = new DoctorRespondJPanel(userProcessContainer,userAccount,patientOrganization,enterprise,ecoe);
        userProcessContainer.add("DoctorRespondJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageProfileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProfileJButtonActionPerformed
        // TODO add your handling code here:
        ManageMyProfileJPanel panel = new ManageMyProfileJPanel(userProcessContainer,userAccount,patientOrganization,enterprise,ecoe);
        userProcessContainer.add("ManageMyProfileJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProfileJButtonActionPerformed

    private void manageVitalSignsAndFitnessRecordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVitalSignsAndFitnessRecordJButtonActionPerformed
        // TODO add your handling code here:
        ManageMyVitalSignsAndFitnessRecordJPanel panel = new ManageMyVitalSignsAndFitnessRecordJPanel(userProcessContainer,userAccount,patientOrganization,enterprise,ecoe);
        userProcessContainer.add("ManageMyVitalSignsAndFitnessRecordJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageVitalSignsAndFitnessRecordJButtonActionPerformed

    private void sendFeedbackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFeedbackJButtonActionPerformed
        // TODO add your handling code here:
        FeedbackToEuipmentManufactureJPanel panel = new FeedbackToEuipmentManufactureJPanel(userProcessContainer,userAccount,patientOrganization,enterprise,ecoe);
        userProcessContainer.add("FeedbackToEuipmentManufactureJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sendFeedbackJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageProfileJButton;
    private javax.swing.JButton manageVitalSignsAndFitnessRecordJButton;
    private javax.swing.JLabel patientNameLable;
    private javax.swing.JButton sendFeedbackJButton;
    // End of variables declaration//GEN-END:variables
}
