/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Ecoe;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.Patient.Record;
import Business.Patient.RecordHistory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sahil Sonawane
 */
public class ViewUpdateRecordDetailsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;    
    private Ecoe ecoe;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientOrganization patientOrganization;
    private Patient patient;
    private Record record;
    /**
     * Creates new form ViewVitalSignsJPanel
     */
    public ViewUpdateRecordDetailsJPanel(JPanel userProcessContainer,UserAccount userAccount, PatientOrganization patientOrganization, Enterprise enterprise,Ecoe ecoSyste,Record record) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoe = ecoe;
        this.userAccount = userAccount;
        this.patientOrganization = (PatientOrganization)patientOrganization;
        this.enterprise = enterprise;
        this.patient= userAccount.getPatient();
        this.record = record;
        populateDetails();
    }

    private void populateDetails() {
        breatheRateJTextField.setText(String.valueOf(record.getbreatheRate()));
        heartrateJTextField.setText(String.valueOf(record.getheartrate()));
        systalicBPJTextField.setText(String.valueOf(record.getsystalicBP()));
        weightJTextField.setText(String.valueOf(record.getweight()));
        standTimeJTextField.setText(String.valueOf(record.getStandTime()));
        movementClockJTextField.setText(String.valueOf(record.getmovementClock()));
        workoutTimeJTextField.setText(String.valueOf(record.getworkoutTime()));
        totTimeJTextField.setText(String.valueOf(record.gettotTime()));
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        breatheRateJTextField = new javax.swing.JTextField();
        heartrateJTextField = new javax.swing.JTextField();
        systalicBPJTextField = new javax.swing.JTextField();
        weightJTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        updateJButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        standTimeJTextField = new javax.swing.JTextField();
        movementClockJTextField = new javax.swing.JTextField();
        workoutTimeJTextField = new javax.swing.JTextField();
        totTimeJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 221, 214));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel16.setText("Weight in pounds");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        breatheRateJTextField.setEnabled(false);
        add(breatheRateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 110, -1));

        heartrateJTextField.setEnabled(false);
        add(heartrateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 110, -1));

        systalicBPJTextField.setEnabled(false);
        add(systalicBPJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 110, -1));

        weightJTextField.setEnabled(false);
        add(weightJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 110, -1));

        jLabel13.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel13.setText("Respiratory rate");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel14.setText("Heart rate");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel15.setText("Systolic blood pressure");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        saveJButton.setBackground(new java.awt.Color(0, 24, 91));
        saveJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        saveJButton.setForeground(new java.awt.Color(255, 255, 255));
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        backJButton.setBackground(new java.awt.Color(0, 24, 91));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        updateJButton.setBackground(new java.awt.Color(0, 24, 91));
        updateJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        updateJButton.setForeground(new java.awt.Color(255, 255, 255));
        updateJButton.setText("Update");
        add(updateJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel9.setText("Move Time (mins)");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel10.setText("Excercise Time (mins)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel11.setText("Total Time (mins)");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        standTimeJTextField.setEnabled(false);
        standTimeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standTimeJTextFieldActionPerformed(evt);
            }
        });
        add(standTimeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 90, -1));

        movementClockJTextField.setEnabled(false);
        add(movementClockJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 90, -1));

        workoutTimeJTextField.setEnabled(false);
        add(workoutTimeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 90, -1));

        totTimeJTextField.setEditable(false);
        totTimeJTextField.setEnabled(false);
        add(totTimeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 90, -1));

        jLabel8.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel8.setText("Stand Time (mins)");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 170, -1));

        jPanel1.setBackground(new java.awt.Color(0, 24, 91));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 33)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("VIEW RECORD DETAILS");
        jPanel1.add(jLabel12);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 590, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void standTimeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standTimeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_standTimeJTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField workoutTimeJTextField;
    private javax.swing.JTextField heartrateJTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField movementClockJTextField;
    private javax.swing.JTextField breatheRateJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JTextField standTimeJTextField;
    private javax.swing.JTextField systalicBPJTextField;
    private javax.swing.JTextField totTimeJTextField;
    private javax.swing.JButton updateJButton;
    private javax.swing.JTextField weightJTextField;
    // End of variables declaration//GEN-END:variables
}
