/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Uber;
import Business.UberCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import java.security.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author hp
 */
public class ViewJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    private Uber uber;
    
    private UberCatalog uberCatalog;

    /**
     * Creates new form ViewJPanel
     */
   

    ViewJPanel(JPanel rightJPanel, Uber uber) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.uber = uber;
        populateUber();
        
        txtBrandName.setEditable(false);
        txtManuYear.setEditable(false);
        txtMaxCapacity.setEditable(false);
        txtMinCapacity.setEditable(false);
        txtSerialNumber.setEditable(false);
        txtModelNumber.setEditable(false);
        txtCity.setEditable(false);
        btnTrue.setEnabled(false);
        btnFalse.setEnabled(false);
        btnExp.setEnabled(false);
        btnNonExp.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtSerialNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaxCapacity = new javax.swing.JTextField();
        txtMinCapacity = new javax.swing.JTextField();
        txtBrandName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtManuYear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack5 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtTimestamp = new javax.swing.JTextField();
        btnTrue = new javax.swing.JCheckBox();
        btnFalse = new javax.swing.JCheckBox();
        btnExp = new javax.swing.JCheckBox();
        btnNonExp = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Enter the Manufacturing Year :");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Enter the Serial Number :");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setText("Enter the Model Number :");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("Is the Car Available? :");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("Enter the City :");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("Maintainance Expiration Certificate :");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("Enter the Max seats Capacity :");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("Enter the Min seats Capacity :");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("                   VIEW");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Enter the Brand Name :");

        btnBack5.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnBack5.setText("< Back");
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnTrue);
        btnTrue.setText("True");

        buttonGroup1.add(btnFalse);
        btnFalse.setText("False");

        buttonGroup2.add(btnExp);
        btnExp.setText("Expired");

        buttonGroup2.add(btnNonExp);
        btnNonExp.setText("Non Expired");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Last Update Occurred On :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack5)
                        .addContainerGap(1396, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnTrue)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFalse))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtModelNumber)
                                                .addComponent(txtSerialNumber)
                                                .addComponent(txtMinCapacity)
                                                .addComponent(txtMaxCapacity)
                                                .addComponent(txtManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(btnExp)
                        .addGap(18, 18, 18)
                        .addComponent(btnNonExp)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack5)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnTrue)
                    .addComponent(btnFalse))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExp)
                    .addComponent(btnNonExp)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
        txtBrandName.setEnabled(true);
        txtManuYear.setEnabled(true);
        txtMaxCapacity.setEnabled(true);
        txtMinCapacity.setEnabled(true);
        txtSerialNumber.setEnabled(true);
        txtModelNumber.setEnabled(true);
        txtCity.setEnabled(true);
        btnTrue.setEnabled(true);
        btnFalse.setEnabled(true);
        btnExp.setEnabled(true);
        btnNonExp.setEnabled(true);
        txtBrandName.setEditable(true);
        txtManuYear.setEditable(true);
        txtMaxCapacity.setEditable(true);
        txtMinCapacity.setEditable(true);
        txtSerialNumber.setEditable(true);
        txtModelNumber.setEditable(true);
        txtCity.setEditable(true);
   
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String brandname = txtBrandName.getText();
        if(brandname == null || brandname.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Brand Name can't be empty");
                return;
            }
        
        String manuYear = txtManuYear.getText();
        if (manuYear == null || manuYear.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Please enter the manufacturing year", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         try {
            Integer.parseInt(txtManuYear.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"You need to put valid value", " Warning", JOptionPane.WARNING_MESSAGE);
        }   
        
         String maxCapa = txtMaxCapacity.getText();
        if (maxCapa == null || maxCapa.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Please enter the Maximum Seats Capacity", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         try {
            Integer.parseInt(txtMaxCapacity.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"You need to put valid value", " Warning", JOptionPane.WARNING_MESSAGE);
        }   
         
          String minCapa = txtMinCapacity.getText();
        if (minCapa == null || minCapa.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Please enter the Minimum Seats Capacity", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         try {
            Integer.parseInt(txtMinCapacity.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"You need to put valid value", " Warning", JOptionPane.WARNING_MESSAGE);
        } 
         
         String serNum = txtSerialNumber.getText();
        if (serNum == null || serNum.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Please enter the Serial Numbers", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         try {
            Integer.parseInt(txtSerialNumber.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"You need to put valid value", " Warning", JOptionPane.WARNING_MESSAGE);
        } 
         
         String modNum = txtModelNumber.getText();
        if (modNum == null || modNum.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Please enter the Model Number", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         
         String avaCity = txtCity.getText();
        if (avaCity == null || avaCity.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Please enter the Model Number", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        
        
        
        
        
        
        
        uber.setBrand(txtBrandName.getText());
        uber.setManufacturedYear(Integer.parseInt(txtManuYear.getText()));
        uber.setMaxSeats(Integer.parseInt(txtMaxCapacity.getText()));
        uber.setMinSeats(Integer.parseInt(txtMinCapacity.getText()));
        uber.setSerialNumber(Integer.parseInt(txtSerialNumber.getText()));
        uber.setModelNumber(txtModelNumber.getText());
        uber.setAvailableCity(txtCity.getText());
        if(btnTrue.isSelected())
        {
            uber.setAvailable(true);
        }
        else{uber.setAvailable(false);
        }
        
        if(btnExp.isSelected()){
            uber.setMaintainanceCerti(true);
        }
        else{
         uber.setMaintainanceCerti(false);
        }
        
        
        SimpleDateFormat date = new SimpleDateFormat("MM/dd/yyyy, hh:mm:ss");
        Date s = new Date();
        txtTimestamp.setText(date.format(s));
        
        JOptionPane.showMessageDialog(null, "Details updated Successfully");
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        // TODO add your handling code here:
       

        this.rightJPanel.remove(this);
        CardLayout layout = (CardLayout) this.rightJPanel.getLayout();
        
        Component[] comps = this.rightJPanel.getComponents();
        for (Component comp : comps)
        {
            if (comp instanceof ManageJPanel){
                ManageJPanel mngp = (ManageJPanel) comp;
                mngp.populateTable(uberCatalog,"all");
            }
        }
        Component[] compss = this.rightJPanel.getComponents();
        for (Component comp : compss)
        {
            if (comp instanceof TableJPanel){
                TableJPanel mngp = (TableJPanel) comp;
                mngp.populateTable(uberCatalog,"all");
            }
        }
        
        layout.previous(rightJPanel);
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void populateUber() {
        //To change body of generated methods, choose Tools | Templates.
        txtBrandName.setText(uber.getBrand());
        txtManuYear.setText(String.valueOf(uber.getManufacturedYear()));
        txtMaxCapacity.setText(String.valueOf(uber.getMaxSeats()));
        txtMinCapacity.setText(String.valueOf(uber.getMinSeats()));
        txtSerialNumber.setText(String.valueOf(uber.getSerialNumber()));
        txtModelNumber.setText(uber.getModelNumber());
        txtCity.setText(uber.getAvailableCity());
        if(uber.isAvailable() == true)
        {
            btnTrue.setEnabled(false);
            btnFalse.setEnabled(false);
            btnTrue.setSelected(true);
        }
        else
        {
            btnTrue.setEnabled(false);
            btnFalse.setEnabled(false);
            btnFalse.setSelected(true);
        }
        if(uber.isMaintainanceCerti()== true)
        {
            btnExp.setEnabled(false);
            btnNonExp.setEnabled(false);
            btnExp.setSelected(true);   
        }
        else
        {
            btnExp.setEnabled(false);
            btnNonExp.setEnabled(false);
            btnNonExp.setSelected(true);
        }
         
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack5;
    private javax.swing.JCheckBox btnExp;
    private javax.swing.JCheckBox btnFalse;
    private javax.swing.JCheckBox btnNonExp;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox btnTrue;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManuYear;
    private javax.swing.JTextField txtMaxCapacity;
    private javax.swing.JTextField txtMinCapacity;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtTimestamp;
    // End of variables declaration//GEN-END:variables
}
