/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabAssistant;

import Business.WorkQueue.PatientDoctorWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sahil Sonawane
 */
public class ProcessTestRequestJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    PatientDoctorWorkRequest request;
    /**
     * Creates new form ProcessTestRequestJPanel
     */
    public ProcessTestRequestJPanel(JPanel userProcessContainer, PatientDoctorWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        submitResultJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 238, 170));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 140, -1));

        jLabel1.setFont(new java.awt.Font("Savoye LET", 0, 30)); // NOI18N
        jLabel1.setText("Test Result");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 110, 40));

        backJButton.setBackground(new java.awt.Color(0, 24, 91));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        submitResultJButton.setBackground(new java.awt.Color(0, 24, 91));
        submitResultJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        submitResultJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitResultJButton.setText("Submit Result");
        submitResultJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitResultJButtonActionPerformed(evt);
            }
        });
        add(submitResultJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 24, 91));

        jLabel13.setBackground(new java.awt.Color(0, 51, 153));
        jLabel13.setFont(new java.awt.Font("Raanana", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TEST REQUEST");
        jPanel1.add(jLabel13);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 620, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabAssistantWorkAreaJPanel dwjp = (LabAssistantWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitResultJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitResultJButtonActionPerformed
        // TODO add your handling code here:
        request.settestingResult(jTextField1.getText());
        request.setstatlab("Complete");
        JOptionPane.showMessageDialog(null, "Test conducted Succesfully");
    }//GEN-LAST:event_submitResultJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton submitResultJButton;
    // End of variables declaration//GEN-END:variables
}
