/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Profile;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author hp
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayPanel
     */
    
    public DisplayJPanel(Profile profile) {
        initComponents();
        displayProfile (profile);
    }
    private void displayProfile(Profile profile)
    {
      String name=profile.getName();
      nameeTextField.setText(name);
      
     String geo=profile.getGeodata();
     geotextfield.setText(geo);
      
     String dob=profile.getDob();
     dobtextfield.setText(dob);
      
        int telenumber=profile.getTelenum();
      teletextfield.setText(String.valueOf(telenumber));
      
        int fax=profile.getFaxnum();
      faxtextfield.setText(String.valueOf(fax));
      
      String email=profile.getEmail();
      emailtextfield.setText(email);
      
        int ssn=profile.getSSN();
   ssntextfield.setText(String.valueOf(ssn));
      
        int medi=profile.getMedinum();
   meditextfield.setText(String.valueOf(medi));
      
        int health=profile.getHealthnum();
     healthtextfield.setText(String.valueOf(health));
     
        String bank=profile.getAccnum();
      banktextfield.setText(bank);
      
      String lic=profile.getLicnum();
     lictextfield.setText(lic);
      
      String plate=profile.getPlatenum();
      serialtextfeld.setText(plate);
      
      
      String serial=profile.getSerialnum();
      seriatextfield.setText(serial);
      
      String linked=profile.getLinkedin();
      linkedtextfield.setText(linked);
      
     String ipad=profile.getIpadd();
      iptextfield.setText(ipad);
      
      String uni=profile.getUninum();
      unitextfield.setText(uni);



      
      
      
      
    String test =profile.getFilename();
    
     
      
    Image imgg = new ImageIcon(profile.getFilename()).getImage();
    jLabel19.setIcon(new ImageIcon(imgg));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nameeTextField = new javax.swing.JTextField();
        geotextfield = new javax.swing.JTextField();
        dobtextfield = new javax.swing.JTextField();
        teletextfield = new javax.swing.JTextField();
        faxtextfield = new javax.swing.JTextField();
        emailtextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ssntextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        meditextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        healthtextfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        banktextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lictextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        serialtextfeld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        seriatextfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        linkedtextfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        iptextfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        unitextfield = new javax.swing.JTextField();
        pathTextField = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));

        jLabel13.setText("Serial No");

        jLabel14.setText("Seria No");

        jLabel15.setText("LinkedIn");

        jLabel16.setText("IP Address");

        nameeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameeTextFieldActionPerformed(evt);
            }
        });

        dobtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobtextfieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("                    Display Profile");

        jLabel2.setText("Name :");

        jLabel3.setText("Geo Location");

        jLabel4.setText("DOB");

        jLabel5.setText("Telephone No");

        lictextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lictextfieldActionPerformed(evt);
            }
        });

        jLabel6.setText("FAX No");

        jLabel7.setText("Email ");

        jLabel8.setText("SSN");

        jLabel9.setText(" Medi record No");

        jLabel10.setText("Health No");

        jLabel11.setText("Bank Acc No");

        jLabel12.setText("LIC No");

        jLabel17.setText("Unique No");

        imgLabel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel21.setText("Profile Picture :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addComponent(jLabel10)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel17)
                            .addComponent(jLabel21))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(806, 806, 806)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                                    .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emailtextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                                    .addComponent(faxtextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teletextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobtextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(geotextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iptextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(linkedtextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seriatextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(serialtextfeld, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lictextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(banktextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(healthtextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(meditextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unitextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ssntextfield))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(309, 309, 309))
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(geotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dobtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(teletextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(faxtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ssntextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(meditextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(healthtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(banktextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lictextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(serialtextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(seriatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(linkedtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(iptextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(unitextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathTextField)
                            .addComponent(jLabel20))
                        .addGap(16, 16, 16)
                        .addComponent(Image))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lictextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lictextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lictextfieldActionPerformed

    private void dobtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobtextfieldActionPerformed

    private void nameeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameeTextFieldActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JTextField banktextfield;
    private javax.swing.JTextField dobtextfield;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JTextField faxtextfield;
    private javax.swing.JTextField geotextfield;
    private javax.swing.JTextField healthtextfield;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JTextField iptextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lictextfield;
    private javax.swing.JTextField linkedtextfield;
    private javax.swing.JTextField meditextfield;
    private javax.swing.JTextField nameeTextField;
    private javax.swing.JLabel pathTextField;
    private javax.swing.JTextField serialtextfeld;
    private javax.swing.JTextField seriatextfield;
    private javax.swing.JTextField ssntextfield;
    private javax.swing.JTextField teletextfield;
    private javax.swing.JTextField unitextfield;
    // End of variables declaration//GEN-END:variables
}
